pipeline:
  compile:
    image: nextcloudci/android:android-44
    commands:
      # build app and assemble APK
      - sh -c "if [ '${FLAVOR}' != 'Analysis' ]; then ./gradlew assemble${FLAVOR}; fi"
    when:
      matrix:
        FLAVOR: [Generic, Gplay]

  analysis:
    image: nextcloudci/android:android-44
    commands:
      - export BRANCH=$(scripts/analysis/getBranchName.sh $GIT_USERNAME $GIT_TOKEN $DRONE_PULL_REQUEST)
      - scripts/analysis/analysis-wrapper.sh $GIT_USERNAME $GIT_TOKEN $BRANCH $LOG_USERNAME $LOG_PASSWORD $DRONE_BUILD_NUMBER $DRONE_PULL_REQUEST
    secrets: [ GIT_USERNAME, GIT_TOKEN, LOG_USERNAME, LOG_PASSWORD ]
    when:
      matrix:
        FLAVOR: Analysis
        
  notify:
      image: drillster/drone-email
      host: $EMAIL_HOST
      port: 587
      username: $EMAIL_USERNAME
      password: $EMAIL_PASSWORD
      from: nextcloud-drone@kaminsky.me
      recipients_only: true
      recipients: [ $EMAIL_RECIPIENTS ]
      secrets: [ EMAIL_USERNAME, EMAIL_PASSWORD, EMAIL_RECIPIENTS, EMAIL_HOST ]
      when:
        event: push
        status: failure
        branch: master

matrix:
  FLAVOR:
    - Generic
    - Gplay
    - Analysis

branches: master
