name: Check

on:
    pull_request:
        branches: [ master, stable-* ]

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                task: [ detekt, ktlint ]
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 8
                uses: actions/setup-java@v2.5.0
                with:
                    distribution: "temurin"
                    java-version: 8.0
            -   name: Check ${{ matrix.task }}
                run: ./gradlew ${{ matrix.task }}
