name: Unit tests

on:
    pull_request:
        branches: [ master, main, stable-* ]
    push:
        branches: [ master, main, stable-* ]

permissions:
    contents: read
    pull-requests: write

concurrency: 
    group: unit-tests-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
            -   name: Set up JDK 17
                uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Run unit tests with coverage
                uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
                with:
                    arguments: testGplayDebugUnit
            -   name: Upload test artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
                with:
                    name: test-results
                    path: app/build/reports/tests/testGplayDebugUnitTest/
